global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"] # Assuming cAdvisor runs on port 8080

remote_write:
  - url: "http://prometheus:9090/write" # Replace with the actual Prometheus write endpoint

